// Generated by CoffeeScript 1.6.1
(function() {
  var aside, traverseTOC;

  $(function() {
    var caption, danksagung, danksagungAfter, figure, footnote, footnotes, heading, img, imgs, index, inlineRef, li, next, ref, title, toc, _i, _j, _k, _len, _len1, _len2;
    title = $('#decayingshelters');
    title.wrap('<section id="front-page"></section>');
    title.after(($('#front-page')).nextUntil('#danksagung'));
    danksagung = $('#danksagung');
    danksagungAfter = danksagung.nextUntil('#inhaltsverzeichnis');
    danksagung.wrap('<div class="float-left"></div>');
    danksagung.after(danksagungAfter);
    imgs = $('img');
    for (_i = 0, _len = imgs.length; _i < _len; _i++) {
      img = imgs[_i];
      img = $(img);
      figure = (img.wrap('<figure></figure>')).parent();
      caption = $('<figcaption></figcaption>');
      caption.html(img.attr('title'));
      figure.append(caption);
      aside(img.parents('p')).append(figure);
    }
    footnotes = $('.footnote');
    for (_j = 0, _len1 = footnotes.length; _j < _len1; _j++) {
      footnote = footnotes[_j];
      ref = $('#' + footnote.href.split('#').pop().replace(':', '\\:'));
      inlineRef = $('<div></div>');
      inlineRef.attr('id', ref.attr('id'));
      inlineRef.addClass('footnote-content');
      inlineRef.append(ref.contents());
      inlineRef.children('p').first().prepend($('<span class="counter">' + footnote.innerHTML + '</span>'));
      ref.remove();
      aside($(footnote).parents('p')).append(inlineRef);
    }
    index = $('#inhaltsverzeichnis');
    toc = $('<ol id="toc"></ol>');
    index.after(toc);
    next = index.nextAll('h2');
    for (_k = 0, _len2 = next.length; _k < _len2; _k++) {
      heading = next[_k];
      $(heading).prev('p').addClass('last-p');
      if (heading.id === 'eidesstattlicheerklrung') {
        continue;
      }
      li = $('<li><a href="#' + heading.id + '">' + heading.innerHTML + '</a></li>');
      toc.append(li);
      traverseTOC(heading, li);
    }
  });

  aside = function(elem) {
    var container;
    container = elem.find('.aside');
    if (container.length < 1) {
      container = $('<div></div>');
      container.addClass('aside');
      elem.prepend(container);
    }
    return container;
  };

  traverseTOC = function(start, parent) {
    var heading, li, next, ol, order, _i, _len;
    if (order > 5) {
      return;
    }
    ol = $('<ol></ol>');
    order = parseInt(start.tagName.split('').pop(), 10);
    order = 'h' + (order + 1);
    next = ($(start)).nextUntil(start.tagName, order);
    for (_i = 0, _len = next.length; _i < _len; _i++) {
      heading = next[_i];
      if (next.tagName === !order) {
        continue;
      }
      li = $('<li><a href="#' + heading.id + '">' + heading.innerHTML + '</a></li>');
      ol.append(li);
      traverseTOC(heading, li);
    }
    if (ol.children().length > 0) {
      return parent.append(ol);
    }
  };

}).call(this);
